apiVersion: v1
kind: PersistentVolume
metadata:
  name: movieworld-mysql-pv
  namespace: movie
  labels:
    app: movieworld
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-ebs 
  awsElasticBlockStore:
    volumeID: vol-08751070450dc4272  # Specify the AWS EBS volume ID
    fsType: ext4  # File system type (e.g., ext4, xfs)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movieworld-mysql-pvc
  namespace: movie
  labels:
    app: movieworld
spec:
  accessModes:
    - ReadWriteOnce  # Should match the access mode of the PV
  storageClassName: mysql-ebs  # Reference the StorageClass used by the PV
  resources:
    requests:
      storage: 200Mi  
