apiVersion: v1
kind: PersistentVolume
metadata:
  name: movieworld-mysql-pv
  labels:
    type: local
    app: movieworld
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/movieworld-mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movieworld-mysql-pvc
  namespace: movie
  labels:
    app: movieworld
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
