apiVersion: v1
kind: Secret
metadata:
  name: movieworld-secrets
type: Opaque
data:
  # These are base64 encoded values
  # echo -n "movieworld" | base64
  database-username: bW92aWV3b3JsZA==
  # echo -n "password" | base64
  database-password: cGFzc3dvcmQ=
