# name: Update Deployment Manifest

# # Allows manual trigger from the Actions tab
# on:
#   workflow_dispatch:  # manual trigger
#     # You *could* add inputs here if needed
#     # inputs:
#     #   environment:
#     #     description: 'Environment (dev/prod)'
#     #     required: true
#     #     default: 'dev'
name: Update Deployment Manifest

on:
  workflow_run:
    workflows: ["MovieWorld CI/CD Pipeline"]
    types:
      - completed
permissions:  
    id-token: write 
    actions: write
    packages: write # Needed for Docker operation
    contents: write

jobs:
 update-manifest:
   runs-on: ubuntu-latest
   env:  
    PROJECT_ID: 'project-stuti-477509' # TODO: update to your Google Cloud project ID
    REGION: 'us-central1' # TODO: update to your region
    SERVICE: 'argocd-poc-repo' # TODO: update to your service name
    IMAGE_NAME: 'movieworld-app-image'  # DOCKER Image Name   

 


    
   steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}


    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Configure docker for GAR
      run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Download image tag
      uses: actions/download-artifact@v3
      with:
          name: image-tag

    - name: Read image tag
      id: read-tag
      run: |
          IMAGE_TAG=$(cat image-tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Show debug
      run: |
        echo "Pulling image: $IMAGE_TAG"

    - name: Pull already built image
      run: |
          docker pull "$IMAGE_TAG"

    # -  name: Get image SHA
    #    run: |
    #       IMAGE_SHA="${{ github.event.workflow_run.outputs.image_sha }}"
    #       echo "IMAGE_SHA=$IMAGE_SHA"
  
    # - name: Pull already built image
    #   run: |
    #       IMAGE="us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:$IMAGE_SHA"
    #       docker pull $IMAGE
    #       echo "Using image: $IMAGE"

    # - name: Deploy to Kubernetes
    #   run: |
    #     IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}"
    #     sed -i "s|image: .*|image: $IMAGE|" kubernetes/manifests/deployment.yaml
    #     kubectl apply -f kubernetes/manifests/deployment.yaml

    # - name: Set image tag
    #   id: set-image-tag
    #   run: |
    #     SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
    #     REPO_NAME=$(basename "$GITHUB_REPOSITORY")
    #     IMAGE_TAG="${REPO_NAME}-${SHORT_SHA}"
    #     echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
 
    - name: Update deployment manifest
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPOSITORY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}"
        sed -i "s|image: .*|image: $IMAGE|" kubernetes/manifests/prod/deployment.yaml
        cat kubernetes/manifests/prod/deployment.yaml

    - name: Commit and push manifest
      run: |
         git config user.name "github-actions"
         git config user.email "github-actions@github.com"
         git add kubernetes/manifests/prod/deployment.yaml
         git commit -m "Update movie deployment to $IMAGE_TAG"
         git push









